export const AUTH = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  ISUSERLOGIN_REQUEST: "ISUSERLOGIN_REQUEST",
  ISUSERLOGIN_SUCCESS: "ISUSERLOGIN_SUCCESS",
  ISUSERLOGIN_FAIL: "ISUSERLOGIN_FAIL",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  CHANGE_AVATAR_REQUEST: "CHANGE_AVATAR_REQUEST",
  CHANGE_AVATAR_SUCCESS: "CHANGE_AVATAR_SUCCESS",
  CHANGE_AVATAR_FAIL: "CHANGE_AVATAR_FAIL",
};
