export const FRIEND = {
  GETFRIENDLIST_REQUEST: "GETFRIENDLIS_REQUEST",
  GETFRIENDLIST_SUCCESS: "GETFRIENDLIS_SUCCESS",
  GETFRIENDLIST_FAIL: "GETFRIENDLIS_FAIL",

  SENDREQUEST_REQUEST: "SENDREQUEST_REQUEST",
  SENDREQUEST_SUCCESS: "SENDREQUEST_SUCCESS",
  SENDREQUEST_FAIL: "SENDREQUEST_FAIL",

  ACCEPTREQUEST_REQUEST: "ACCEPTREQUEST_REQUEST",
  ACCEPTREQUEST_SUCCESS: "ACCEPTREQUEST_SUCCESS",
  ACCEPTREQUEST_FAIL: "ACCEPTREQUEST_FAIL",

  UNFRIEND_REQUEST: "UNFRIEND_REQUEST",
  UNFRIEND_SUCCESS: "UNFRIEND_SUCCESS",
  UNFRIEND_FAIL: "UNFRIEND_FAIL",
};
