export const FRIEND = {
  SENDREQUEST_REQUEST: "SENDREQUEST_REQUEST",
  SENDREQUEST_SUCCESS: "SENDREQUEST_SUCCESS",
  SENDREQUEST_FAIL: "SENDREQUEST_FAIL",

  ACCEPTREQUEST_REQUEST: "ACCEPTREQUEST_REQUEST",
  ACCEPTREQUEST_SUCCESS: "ACCEPTREQUEST_SUCCESS",
  ACCEPTREQUEST_FAIL: "ACCEPTREQUEST_FAIL",
};
