export const MESSAGE = {
  GETMESSAGE_REQUEST: "GETMESSAGE_REQUEST",
  GETMESSAGE_SUCCESS: "GETMESSAGE_SUCCESS",
  GETMESSAGE_FAIL: "GETMESSAGE_FAIL",

  SENDMESSAGE_REQUEST: "SENDMESSAGE_REQUEST",
  SENDMESSAGE_SUCCESS: "SENDMESSAGE_SUCCESS",
  SENDMESSAGE_FAIL: "SENDMESSAGE_FAIL",
};
