export const POST = {
  POST_REQUEST: "POST_REQUEST",
  POST_FAIL: "POST_FAIL",
  POST_SUCCESS: "POST_SUCCESS",

  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAIL: "CREATE_POST_FAIL",

  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAIL: "DELETE_POST_FAIL",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAIL: "UPDATE_POST_FAIL",
};
