export const USER = {
  USER_REQUEST: "USER_REQUEST",
  USER_SUCCESS: "USER_SUCCESS",
  USER_FAIL: "USER_FAIL",

  FINDNAMEUSER_REQUEST: "FINDNAMEUSER_REQUEST",
  FINDNAMEUSER_SUCCESS: "FINDNAMEUSER_SUCCESS",
  FINDNAMEUSER_FAIL: "FINDNAMEUSER_FAIL",
};
